kind: pipeline
name: default

steps:
    - name: build
      image: docker
      volumes:
        - name: docker_socket
          path: /var/run/docker.sock
      commands:
        - docker build -t my/tag .


volumes:
    - name: docker_socket
      host:
        path: /var/run/docker.sock
