kind: pipeline
type: docker
name: default
steps:
##########
- name: pull
  image: plugins/ecr
  commands:
    - docker pull nginx
    - docker save -o nginx.tar nginx
  volumes:
  - name: docker
    path: /var/lib/
volumes:
- name: docker
  host:
    path: /var/lib/docker
